# Generated by Django 3.2.9 on 2021-12-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of file here.', max_length=255)),
                ('url', models.URLField(blank=True, help_text='Url where to embed file directly', null=True)),
                ('file_url', models.FileField(help_text='Upload your audio file here', max_length=255, upload_to='')),
                ('created_on', models.BooleanField(help_text='Is your file active for furthur processing', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Convert Requests',
            },
        ),
    ]
