# Generated by Django 3.2.9 on 2021-12-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertrequest',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
